export const emojiCatalog = [
  ["📄", "page document file paper"],
  ["📝", "memo note write writing edit"],
  ["📔", "notebook journal diary"],
  ["📓", "notebook journal"],
  ["📒", "ledger notebook"],
  ["📚", "books library study reading"],
  ["🗒️", "notepad notes"],
  ["📋", "clipboard checklist tasks"],
  ["🗂️", "organize index folders"],
  ["📁", "folder directory project"],
  ["📂", "open folder directory project"],
  ["📌", "pin pinned important"],
  ["📍", "location map pin place"],
  ["🔖", "bookmark favorite save"],
  ["🏷️", "tag label category"],
  ["✅", "done complete check success"],
  ["☑️", "checkbox task done"],
  ["⭐", "star favorite important"],
  ["🌟", "glowing star favorite"],
  ["💡", "idea light inspiration"],
  ["🔥", "fire hot priority"],
  ["⚡", "lightning energy fast"],
  ["🚀", "rocket launch startup"],
  ["🎯", "target goal objective"],
  ["🎨", "art design creative palette"],
  ["🛠️", "tools build repair work"],
  ["🔧", "wrench tool settings repair"],
  ["⚙️", "gear settings configuration"],
  ["🧩", "puzzle plugin component"],
  ["🔬", "microscope science research"],
  ["🧪", "experiment test science"],
  ["💻", "laptop computer code development"],
  ["🖥️", "desktop computer monitor"],
  ["⌨️", "keyboard typing code"],
  ["🖱️", "mouse computer"],
  ["📱", "phone mobile"],
  ["🌐", "web internet globe network"],
  ["🔒", "lock secure private security"],
  ["🔓", "unlock open security"],
  ["🔑", "key access password"],
  ["🛡️", "shield security protection"],
  ["📊", "chart analytics statistics data"],
  ["📈", "growth chart increase business"],
  ["📉", "decline chart decrease"],
  ["💰", "money finance budget wealth"],
  ["💵", "cash dollar money"],
  ["💳", "credit card payment finance"],
  ["🧾", "receipt invoice expense"],
  ["🗓️", "calendar schedule date plan"],
  ["📅", "calendar date event"],
  ["⏰", "clock alarm time deadline"],
  ["⏳", "hourglass waiting time"],
  ["✏️", "pencil write edit"],
  ["🖊️", "pen write sign"],
  ["📎", "paperclip attachment"],
  ["🔗", "link connection"],
  ["❗", "important warning exclamation"],
  ["❓", "question help"],
  ["💬", "comment chat message"],
  ["📣", "announcement marketing"],
  ["🔔", "notification reminder bell"],
  ["🏠", "house home building"],
  ["🏡", "house home garden residential"],
  ["🏢", "office building company work"],
  ["🏭", "factory industry manufacturing"],
  ["🏫", "school education building"],
  ["🏥", "hospital health medical"],
  ["🏦", "bank finance building"],
  ["🏛️", "government museum institution"],
  ["🏗️", "construction building project"],
  ["🧠", "brain knowledge thinking mind"],
  ["❤️", "heart love health favorite"],
  ["🧡", "orange heart love"],
  ["💛", "yellow heart love"],
  ["💚", "green heart love"],
  ["💙", "blue heart love"],
  ["💜", "purple heart love"],
  ["🤍", "white heart love"],
  ["🤝", "handshake agreement partnership"],
  ["👥", "people team users group"],
  ["👤", "person user profile"],
  ["🧑‍💻", "developer programmer code person"],
  ["👨‍💼", "business manager work"],
  ["👩‍💼", "business manager work"],
  ["🎓", "graduation education learning"],
  ["📖", "book reading documentation"],
  ["🔍", "search inspect discover"],
  ["🔎", "search inspect discover"],
  ["🧭", "compass navigation direction"],
  ["🗺️", "map travel roadmap"],
  ["🚩", "flag milestone goal"],
  ["🏁", "finish flag complete"],
  ["🚧", "construction work progress"],
  ["💼", "briefcase business work job"],
  ["📦", "package product shipping"],
  ["🛒", "cart shopping commerce"],
  ["🛍️", "shopping retail"],
  ["🎁", "gift present reward"],
  ["📧", "email mail message"],
  ["📨", "mail inbox message"],
  ["📞", "phone call contact"],
  ["🎥", "video movie camera"],
  ["📷", "camera photo photography"],
  ["🎵", "music audio note"],
  ["🎧", "headphones audio music"],
  ["🎙️", "microphone podcast audio"],
  ["🎮", "game controller gaming"],
  ["🏆", "trophy award achievement"],
  ["🥇", "gold medal first achievement"],
  ["🎉", "celebration party success"],
  ["✨", "sparkles new magic"],
  ["🌱", "seedling growth nature"],
  ["🌿", "plant nature green"],
  ["🌳", "tree nature outdoors"],
  ["🌲", "evergreen tree nature"],
  ["🌻", "flower sunflower nature"],
  ["🌎", "earth world global"],
  ["☀️", "sun weather bright"],
  ["🌙", "moon night dark"],
  ["☁️", "cloud weather storage"],
  ["🌈", "rainbow color"],
  ["🌊", "wave water ocean"],
  ["⛰️", "mountain outdoors"],
  ["🏖️", "beach vacation travel"],
  ["✈️", "airplane travel flight"],
  ["🚗", "car vehicle travel"],
  ["🚲", "bike bicycle travel"],
  ["🚆", "train travel transit"],
  ["☕", "coffee drink cafe"],
  ["🍵", "tea drink"],
  ["🍎", "apple food health"],
  ["🥗", "salad food health"],
  ["🍽️", "food meal restaurant"],
  ["🧘", "meditation wellness calm"],
  ["🏃", "running fitness health"],
  ["🏋️", "fitness gym strength"],
  ["⚽", "soccer sport"],
  ["🏀", "basketball sport"],
  ["🏈", "football sport"],
  ["🩺", "medical health doctor"],
  ["💊", "medicine health"],
  ["🧬", "dna biology science"],
  ["🧮", "calculator math finance"],
  ["📐", "design ruler geometry"],
  ["📏", "ruler measurement"],
  ["♻️", "recycle sustainability"],
  ["🔄", "refresh sync repeat"],
  ["⬆️", "up upload increase"],
  ["⬇️", "down download decrease"],
  ["➡️", "right next forward"],
  ["⬅️", "left back previous"],
  ["➕", "plus add new"],
  ["➖", "minus remove"],
  ["✖️", "close delete multiply"],
  ["⭕", "circle status"],
  ["🟢", "green status online"],
  ["🟡", "yellow status pending"],
  ["🔴", "red status blocked"],
  ["🔵", "blue status"],
  ["🟣", "purple status"],
];

export function searchEmojis(query) {
  const terms = String(query || "")
    .toLowerCase()
    .trim()
    .split(/\s+/)
    .filter(Boolean);
  if (terms.length === 0) return emojiCatalog;
  return emojiCatalog.filter(([, keywords]) =>
    terms.every((term) => keywords.includes(term))
  );
}
